### ISSUE TITLE
DEV-18: Change the layout of the footer

### ISSUE THREAD

**Issue by KovDimaY** [KovDimaY/SimpleChat-Socket.io#36]
At the moment the footer is fixed at the bottom and it blocks a big part of the screen. I do not like this because on the mobile devices it makes the app not comfortable to use and also it looks not very nice:
![image](https://user-images.githubusercontent.com/26466644/46580884-ce671000-ca2d-11e8-9c90-6c6017a03a03.png)

I know that it was spent some effort to make it fixed like that, but I think it will be better to change it to the normal way how the usual footers are made: it is on the very bottom of the screen and if the user wants to see it - the page should be scrolled down.

To work on this issue, please use a branch **DEV-18** created from **devel**. When the work is finished - create a PR to the **devel** branch. At the end of each development circles, code from the **devel** branch (if everything is ok) goes to the **master** branch and deploys to production.ct.

**Comment by TetianaKlymchuk** [comment]
I want to take this one! :D

**Comment by KovDimaY** [comment]
Yes, sure! Thank you!

**Comment by TetianaKlymchuk** [comment]
Fixed! Now the pages look like this:
1) Home:
![image](https://user-images.githubusercontent.com/28005338/46585228-6c7aca80-ca6e-11e8-87e2-5b0c7ca79641.png)

![image](https://user-images.githubusercontent.com/28005338/46585236-85837b80-ca6e-11e8-9e5d-0a41fbc0c639.png)

2) Chat:
![image](https://user-images.githubusercontent.com/28005338/46585249-bebbeb80-ca6e-11e8-8dbd-0ac7b6c3abf1.png)
I decided to delete footer on this page because it looks ugly and I think this page is better without footer.

3) 404:
![image](https://user-images.githubusercontent.com/28005338/46585257-e3b05e80-ca6e-11e8-9ee7-ccc47488a7de.png)

![image](https://user-images.githubusercontent.com/28005338/46585260-f034b700-ca6e-11e8-9bc9-63b6b3cc7ba5.png)

Let me know what do you think? :)

**Comment by KovDimaY** [comment]
Perfect! I like the result, thank you! Create a PR please and let's move forward! 👍

**Comment by KovDimaY** [comment]
Perfect! Approved and merged! Great job! 👍
